global:
  scrape_interval: 15s # El sistema pedirá métricas cada 15 segundos
  evaluation_interval: 15s

# Reglas de monitoreo para nuestro stack de Big Data
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spark-cluster'
    static_configs:
      - targets: ['spark-master:8080', 'spark-worker:8081']

  - job_name: 'flink-cluster'
    static_configs:
      - targets: ['flink-jobmanager:8081']