apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring # Aísla las herramientas de administración del tráfico de Big Data
data:
  prometheus.yml: |
    global:
      # scrape_interval: Resolución temporal (15s). Evita perder picos de RAM 
      # sin saturar la red con tráfico de auditoría innecesario.
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spark-pods'
        # kubernetes_sd_configs (role: pod): Descubrimiento automático de contenedores. 
        # Busca dinámicamente los Workers sin necesidad de configurar IPs estáticas.
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                # namespaces: Filtro crucial que resuelve el error 'No targets'. Fuerza a mirar 
                # solo este entorno, agilizando la carga y adaptándose a los permisos del ClusterRole.
                - "datastream-bigdata"
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  containers:
  - name: prometheus
    image: prom/prometheus:latest
    args:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
    - containerPort: 9090 # Puerto nativo de la interfaz web de Prometheus
    volumeMounts:
      - name: config-volume
        mountPath: /etc/prometheus # Mapea las configuraciones del ConfigMap dentro del contenedor
  volumes:
    - name: config-volume
      configMap:
        name: prometheus-config
