apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/hdfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
# Paso 4: Creacion del manifiesto de almacenamiento persistente pv-hdfs
